# Generated by Django 2.1.5 on 2019-04-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notenerfassung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lehrer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lehrer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='password',
        ),
        migrations.AddField(
            model_name='lehrer',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schueler',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
