# Generated by Django 2.1.5 on 2019-04-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notenerfassung', '0002_auto_20190404_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lehrer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='schueler',
            old_name='user_id',
            new_name='user',
        ),
    ]
