# Generated by Django 2.1.5 on 2019-04-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notenerfassung', '0003_auto_20190404_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fach',
            options={'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='klasse',
            options={'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AlterModelOptions(
            name='lehrer',
            options={'verbose_name': 'Lehrer', 'verbose_name_plural': 'Lehrer'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Noten', 'verbose_name_plural': 'Noten'},
        ),
        migrations.AlterModelOptions(
            name='schueler',
            options={'verbose_name': 'Schüler', 'verbose_name_plural': 'Schüler'},
        ),
        migrations.AlterModelOptions(
            name='unterrichtet',
            options={'verbose_name': 'Unterrichtet', 'verbose_name_plural': 'Unterrichtet'},
        ),
    ]
