# Generated by Django 2.1.5 on 2019-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notenerfassung', '0007_auto_20190409_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrer',
            name='isAdmin',
        ),
    ]
